# This is an example integration that demonstrates how to add a function that automatically runs periodically (in this case 5 seconds)

import threading
from time import sleep
from flask import json

def add_person_every_minute(app):
    with app.test_request_context():
        while True:
            data = json.dumps({'name': 'AutoGenerated', 'auto_test': True})
            # Mimic a POST request to the create_entity endpoint
            response = app.test_client().post('/people', data=data, content_type='application/json')
            print(f"added with response: {response.status}")
            sleep(5)  # Every minute

def start_adding_persons(app):
    thread = threading.Thread(target=add_person_every_minute, args=(app,))
    thread.start()

def register(integration_manager):
    start_adding_persons(integration_manager.app)
